"""Cycles synthetic weather + outfit scenarios for visual QA without the weather API."""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from . import outfit


def _w(
    *,
    temp: float,
    rain: float = 0,
    snow: float = 0,
    clouds: int = 50,
    wind_kmh: float = 10,
    hour: int = 12,
    description: str = "",
    icon: str = "02d",
    condition_id: int = 801,
) -> Dict[str, Any]:
    return {
        "temp": temp,
        "rain": rain,
        "snow": snow,
        "clouds": clouds,
        "wind_kmh": wind_kmh,
        "hour": hour,
        "description": description,
        "icon": icon,
        "condition_id": condition_id,
    }


def _fc(
    *,
    hour: int,
    hours_from_now: int,
    temp: float,
    rain: float = 0,
    snow: float = 0,
    clouds: int = 50,
    wind_kmh: float = 10,
    description: str = "",
    icon: str = "02d",
    condition_id: int = 801,
) -> Dict[str, Any]:
    """Tranche prévision (mêmes clés que ``weather.get_forecast``)."""
    return {
        "hour": hour,
        "hours_from_now": hours_from_now,
        "temp": temp,
        "rain": rain,
        "snow": snow,
        "clouds": clouds,
        "wind_kmh": wind_kmh,
        "description": description,
        "icon": icon,
        "condition_id": condition_id,
    }


# Chaque scénario : météo courante + prévisions qui ajoutent 2–3 accessoires futurs
# (via ``get_outfit_with_identity(weather, forecast, ...)`` — voir ``DebugPreview``).
SCENARIOS: List[Dict[str, Any]] = [
    {
        "label": "Heavy rain + cold (umbrella, rain_boots)",
        "weather": _w(
            temp=6,
            rain=8,
            clouds=92,
            wind_kmh=12,
            hour=14,
            description="Pluie forte",
            icon="10d",
            condition_id=502,
        ),
        "forecast": [
            _fc(
                hour=17,
                hours_from_now=3,
                temp=4,
                rain=0,
                snow=0,
                clouds=65,
                wind_kmh=38,
                description="Venteux",
                icon="04d",
            ),
            _fc(
                hour=20,
                hours_from_now=6,
                temp=-4,
                rain=0,
                snow=1.2,
                clouds=92,
                wind_kmh=14,
                description="Neige",
                icon="13d",
                condition_id=601,
            ),
            _fc(
                hour=11,
                hours_from_now=9,
                temp=1,
                rain=0.6,
                snow=0,
                clouds=96,
                wind_kmh=10,
                description="Verglas",
                icon="13d",
                condition_id=511,
            ),
        ],
    },
    {
        "label": "Snow + freezing (beanie, boots, scarf)",
        "weather": _w(
            temp=-7,
            snow=1.5,
            clouds=85,
            wind_kmh=8,
            hour=11,
            description="Neige",
            icon="13d",
            condition_id=601,
        ),
        "forecast": [
            _fc(
                hour=15,
                hours_from_now=3,
                temp=8,
                rain=6,
                snow=0,
                clouds=88,
                wind_kmh=14,
                description="Pluie",
                icon="10d",
                condition_id=502,
            ),
            _fc(
                hour=11,
                hours_from_now=6,
                temp=24,
                rain=0,
                snow=0,
                clouds=22,
                wind_kmh=8,
                description="Éclaircies",
                icon="02d",
                condition_id=801,
            ),
            _fc(
                hour=14,
                hours_from_now=9,
                temp=-5,
                rain=0,
                snow=0.8,
                clouds=90,
                wind_kmh=12,
                description="Neige",
                icon="13d",
                condition_id=601,
            ),
        ],
    },
    {
        "label": "Ice — cold rain + freezing rain id (crampons)",
        "weather": _w(
            temp=0,
            rain=0.8,
            snow=0,
            clouds=95,
            wind_kmh=14,
            hour=8,
            description="Pluie verglaçante",
            icon="13d",
            condition_id=511,
        ),
        "forecast": [
            _fc(
                hour=11,
                hours_from_now=3,
                temp=5,
                rain=6,
                snow=0,
                clouds=85,
                wind_kmh=12,
                description="Pluie forte",
                icon="10d",
            ),
            _fc(
                hour=14,
                hours_from_now=6,
                temp=28,
                rain=0,
                snow=0,
                clouds=8,
                wind_kmh=6,
                description="Soleil",
                icon="01d",
                condition_id=800,
            ),
            _fc(
                hour=17,
                hours_from_now=9,
                temp=-6,
                rain=0,
                snow=1.0,
                clouds=88,
                wind_kmh=10,
                description="Neige",
                icon="13d",
                condition_id=601,
            ),
        ],
    },
    {
        "label": "Full sun midday — hot (sun_screen, hat)",
        "weather": _w(
            temp=26,
            clouds=10,
            wind_kmh=6,
            hour=12,
            description="Ensoleillé",
            icon="01d",
            condition_id=800,
        ),
        "forecast": [
            _fc(
                hour=15,
                hours_from_now=3,
                temp=18,
                rain=1.2,
                snow=0,
                clouds=72,
                wind_kmh=10,
                description="Pluie",
                icon="10d",
            ),
            _fc(
                hour=18,
                hours_from_now=6,
                temp=2,
                rain=0,
                snow=0,
                clouds=55,
                wind_kmh=37,
                description="Venteux",
                icon="04d",
            ),
            _fc(
                hour=21,
                hours_from_now=9,
                temp=-3,
                rain=0,
                snow=1.1,
                clouds=92,
                wind_kmh=12,
                description="Neige",
                icon="13d",
                condition_id=601,
            ),
        ],
    },
    {
        "label": "Partly cloudy — sunglasses",
        "weather": _w(
            temp=22,
            clouds=25,
            wind_kmh=5,
            hour=12,
            description="Partiellement nuageux",
            icon="02d",
            condition_id=801,
        ),
        "forecast": [
            _fc(
                hour=14,
                hours_from_now=3,
                temp=16,
                rain=0.8,
                snow=0,
                clouds=80,
                wind_kmh=11,
                description="Averses",
                icon="10d",
            ),
            _fc(
                hour=17,
                hours_from_now=6,
                temp=5,
                rain=5,
                snow=0,
                clouds=92,
                wind_kmh=16,
                description="Pluie",
                icon="10d",
                condition_id=502,
            ),
            _fc(
                hour=9,
                hours_from_now=9,
                temp=-2,
                rain=0,
                snow=0.6,
                clouds=94,
                wind_kmh=10,
                description="Neige",
                icon="13d",
                condition_id=601,
            ),
        ],
    },
    {
        "label": "Strong wind + cold (scarf)",
        "weather": _w(
            temp=7,
            clouds=55,
            wind_kmh=38,
            hour=15,
            description="Venteux",
            icon="04d",
            condition_id=804,
        ),
        "forecast": [
            _fc(
                hour=17,
                hours_from_now=3,
                temp=11,
                rain=1.5,
                snow=0,
                clouds=82,
                wind_kmh=25,
                description="Pluie",
                icon="10d",
            ),
            _fc(
                hour=19,
                hours_from_now=6,
                temp=4,
                rain=5,
                snow=0,
                clouds=95,
                wind_kmh=20,
                description="Pluie forte",
                icon="10d",
            ),
            _fc(
                hour=8,
                hours_from_now=9,
                temp=-4,
                rain=0,
                snow=0.9,
                clouds=91,
                wind_kmh=14,
                description="Neige",
                icon="13d",
                condition_id=601,
            ),
        ],
    },
    {
        "label": "Mild cloudy — no accessories",
        "weather": _w(
            temp=20,
            clouds=72,
            wind_kmh=8,
            hour=14,
            description="Nuageux",
            icon="03d",
            condition_id=802,
        ),
        "forecast": [
            _fc(
                hour=16,
                hours_from_now=3,
                temp=17,
                rain=0.9,
                snow=0,
                clouds=78,
                wind_kmh=12,
                description="Pluie",
                icon="10d",
            ),
            _fc(
                hour=18,
                hours_from_now=6,
                temp=12,
                rain=5,
                snow=0,
                clouds=92,
                wind_kmh=14,
                description="Pluie forte",
                icon="10d",
            ),
            _fc(
                hour=10,
                hours_from_now=9,
                temp=-1,
                rain=0,
                snow=0.7,
                clouds=94,
                wind_kmh=10,
                description="Neige",
                icon="13d",
                condition_id=601,
            ),
        ],
    },
    {
        "label": "Extreme cold — beanie (verycold → cold sprite)",
        "weather": _w(
            temp=-16,
            clouds=45,
            wind_kmh=10,
            hour=12,
            description="Très froid",
            icon="02d",
            condition_id=802,
        ),
        "forecast": [
            _fc(
                hour=14,
                hours_from_now=3,
                temp=-12,
                rain=0.8,
                snow=0,
                clouds=88,
                wind_kmh=12,
                description="Pluie",
                icon="10d",
            ),
            _fc(
                hour=16,
                hours_from_now=6,
                temp=-8,
                rain=4,
                snow=0,
                clouds=94,
                wind_kmh=14,
                description="Pluie forte",
                icon="10d",
            ),
            _fc(
                hour=7,
                hours_from_now=9,
                temp=0,
                rain=0.4,
                snow=0,
                clouds=97,
                wind_kmh=8,
                description="Verglas",
                icon="13d",
                condition_id=511,
            ),
        ],
    },
    {
        "label": "Extreme heat (veryhot, sun_screen, hat)",
        "weather": _w(
            temp=36,
            clouds=6,
            wind_kmh=4,
            hour=14,
            description="Canicule",
            icon="01d",
            condition_id=800,
        ),
        "forecast": [
            _fc(
                hour=16,
                hours_from_now=3,
                temp=24,
                rain=1,
                snow=0,
                clouds=70,
                wind_kmh=12,
                description="Pluie",
                icon="10d",
            ),
            _fc(
                hour=18,
                hours_from_now=6,
                temp=10,
                rain=0,
                snow=0,
                clouds=50,
                wind_kmh=36,
                description="Venteux",
                icon="04d",
            ),
            _fc(
                hour=21,
                hours_from_now=9,
                temp=-2,
                rain=0,
                snow=0.5,
                clouds=93,
                wind_kmh=16,
                description="Neige",
                icon="13d",
                condition_id=601,
            ),
        ],
    },
    {
        "label": "Rain at night — umbrella only",
        "weather": _w(
            temp=11,
            rain=2.5,
            clouds=100,
            wind_kmh=14,
            hour=22,
            description="Pluie",
            icon="10n",
            condition_id=500,
        ),
        "forecast": [
            _fc(
                hour=10,
                hours_from_now=3,
                temp=18,
                rain=0,
                snow=0,
                clouds=72,
                wind_kmh=10,
                description="Nuageux",
                icon="03d",
            ),
            _fc(
                hour=13,
                hours_from_now=6,
                temp=14,
                rain=2,
                snow=0,
                clouds=85,
                wind_kmh=33,
                description="Pluie / vent",
                icon="10d",
            ),
            _fc(
                hour=16,
                hours_from_now=9,
                temp=4,
                rain=5,
                snow=0,
                clouds=94,
                wind_kmh=18,
                description="Pluie forte",
                icon="10d",
                condition_id=502,
            ),
        ],
    },
    {
        "label": "Forecast — clear then rain (future umbrella)",
        "weather": _w(
            temp=22,
            clouds=55,
            wind_kmh=9,
            hour=12,
            description="Nuages épars",
            icon="03d",
            condition_id=802,
        ),
        "forecast": [
            _fc(
                hour=15,
                hours_from_now=3,
                temp=17,
                rain=2,
                snow=0,
                clouds=80,
                wind_kmh=12,
                description="Pluie",
                icon="10d",
            ),
            _fc(
                hour=18,
                hours_from_now=6,
                temp=10,
                rain=5,
                snow=0,
                clouds=92,
                wind_kmh=16,
                description="Pluie forte",
                icon="10d",
                condition_id=502,
            ),
            _fc(
                hour=9,
                hours_from_now=9,
                temp=-3,
                rain=0,
                snow=0.8,
                clouds=94,
                wind_kmh=12,
                description="Neige",
                icon="13d",
                condition_id=601,
            ),
        ],
    },
    {
        "label": "Hot night — hat (cap/sun rules off)",
        "weather": _w(
            temp=31,
            clouds=12,
            wind_kmh=6,
            hour=21,
            description="Clair",
            icon="01n",
            condition_id=800,
        ),
        "forecast": [
            _fc(
                hour=8,
                hours_from_now=3,
                temp=20,
                rain=1,
                snow=0,
                clouds=78,
                wind_kmh=11,
                description="Pluie",
                icon="10d",
            ),
            _fc(
                hour=11,
                hours_from_now=6,
                temp=3,
                rain=0.6,
                snow=0,
                clouds=96,
                wind_kmh=9,
                description="Verglas",
                icon="13d",
                condition_id=511,
            ),
            _fc(
                hour=14,
                hours_from_now=9,
                temp=-5,
                rain=0,
                snow=1.0,
                clouds=91,
                wind_kmh=12,
                description="Neige",
                icon="13d",
                condition_id=601,
            ),
        ],
    },
]


class DebugPreview:
    """Advances through ``SCENARIOS`` every ``debug_preview_interval_seconds``."""

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        cfg = config or {}
        raw = cfg.get("debug_preview_interval_seconds", 5)
        try:
            self._interval = max(0.5, float(raw))
        except (TypeError, ValueError):
            self._interval = 5.0
        self._idx = 0
        self._last_switch: Optional[float] = None

    def next_frame(self, now: float, gender: str, number: int) -> Dict[str, Any]:
        """
        Return ``label``, ``weather``, and ``outfit`` for the active scenario.

        ``gender`` and ``number`` are passed through to ``get_outfit_with_identity``.
        """
        if self._last_switch is None:
            self._last_switch = now
        elif now - self._last_switch >= self._interval:
            self._idx = (self._idx + 1) % len(SCENARIOS)
            self._last_switch = now

        scen = SCENARIOS[self._idx]
        weather = scen["weather"]
        forecast: List[Dict[str, Any]] = scen.get("forecast") or []
        outfit_dict = outfit.get_outfit_with_identity(weather, forecast, gender, number)
        return {
            "label": scen["label"],
            "weather": weather,
            "outfit": outfit_dict,
        }
